language: cpp
compiler:
  - g++
  - clang
# Change this to your needs

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq [packages list]
 - sudo apt-get install -qq gcc-4.8 g++-4.8 
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
 - sudo apt-get install -q gcc-4.8
 - sudo apt-get install -q g++-4.8
 - sudo apt-get build-dep glfw3
 - sudo apt-get install cmake xorg-dev libglu1-mesa-dev
 - cd glfw-3.0.4
 - rehash
 - cmake -G "Unix Makefiles"
 - make
 - sudo make install

for_install
 - g++ -std=c++11 *.cpp *.h Game -lglfw3 -lGL -lm -lXrandr -lXi -lX11 -lXxf86vm -lpthread
